### ISSUE TITLE
mode verbose

### ISSUE THREAD

**Issue by 4zv4l** [SaigoNoo/jpscanvf#1]
À la place de conseiller aux users de changer une ligne de code tu pourrais faire un argument au script.  
par example `-v` ou `--verbose` qui permettrait de voir plus de détails.
(c'est juste un conseil, tu peux fermer l'issue si tu préfères laisser ça comme c'est ^^)

**Comment by GreekBoy-dev** [comment]
Je sais bien, mais ce code va bientôt être écrasé par un autre en Python où ce que tu me proposes sera appliqué ! Mais merci quand même pour ton avis :)
